In [1]:
import pandas as pd
import numpy as np

perf = pd.read_csv(
    "../data/processed/clean_scheme_performance.csv"
)

print(perf.columns)
print(perf.shape)

Index(['amfi_code', 'scheme_name', 'fund_house', 'category', 'plan',
       'return_1yr_pct', 'return_3yr_pct', 'return_5yr_pct',
       'benchmark_3yr_pct', 'alpha', 'beta', 'sharpe_ratio', 'sortino_ratio',
       'std_dev_ann_pct', 'max_drawdown_pct', 'aum_crore', 'expense_ratio_pct',
       'morningstar_rating', 'risk_grade'],
      dtype='object')
(40, 19)

In [2]:
sharpe = (
    perf[
        [
            "scheme_name",
            "sharpe_ratio"
        ]
    ]
    .sort_values(
        "sharpe_ratio",
        ascending=False
    )
)

sharpe.head(10)

                                          scheme_name  sharpe_ratio
14           ICICI Pru Liquid Fund - Regular - Growth          7.68
23               Kotak Liquid Fund - Regular - Growth          6.18
30                ABSL Liquid Fund - Regular - Growth          5.14
9        HDFC Short Term Debt Fund - Regular - Growth          1.84
4        SBI Magnum Gilt Fund - Regular Plan - Growth          1.52
19  Nippon India Gilt Securities Fund - Regular - ...          1.33
34      Mirae Asset Large Cap Fund - Regular - Growth          1.06
5           HDFC Top 100 Fund - Regular Plan - Growth          1.06
11          ICICI Pru Bluechip Fund - Direct - Growth          1.03
15     Nippon India Large Cap Fund - Regular - Growth          1.00

In [3]:
sharpe.to_csv(
    "../reports/fund_sharpe_ranks.csv",
    index=False
)

print("Saved")

Saved

In [4]:
sortino = (
    perf[
        [
            "scheme_name",
            "sortino_ratio"
        ]
    ]
    .sort_values(
        "sortino_ratio",
        ascending=False
    )
)

sortino.head(10)

                                          scheme_name  sortino_ratio
14           ICICI Pru Liquid Fund - Regular - Growth          10.37
23               Kotak Liquid Fund - Regular - Growth           9.70
30                ABSL Liquid Fund - Regular - Growth           8.76
9        HDFC Short Term Debt Fund - Regular - Growth           2.79
19  Nippon India Gilt Securities Fund - Regular - ...           2.38
4        SBI Magnum Gilt Fund - Regular Plan - Growth           2.11
5           HDFC Top 100 Fund - Regular Plan - Growth           1.70
15     Nippon India Large Cap Fund - Regular - Growth           1.68
3           SBI Small Cap Fund - Direct Plan - Growth           1.67
34      Mirae Asset Large Cap Fund - Regular - Growth           1.66

In [5]:
sortino.to_csv(
    "../reports/fund_sortino_ranks.csv",
    index=False
)

In [6]:
alpha = (
    perf[
        [
            "scheme_name",
            "alpha"
        ]
    ]
    .sort_values(
        "alpha",
        ascending=False
    )
)

alpha.head()

                                      scheme_name  alpha
9    HDFC Short Term Debt Fund - Regular - Growth   1.98
21  Kotak Emerging Equity Fund - Regular - Growth   1.91
14       ICICI Pru Liquid Fund - Regular - Growth   1.85
22         Kotak Flexicap Fund - Regular - Growth   1.85
29         ABSL Small Cap Fund - Regular - Growth   1.84

In [7]:
alpha.to_csv(
    "../reports/alpha_analysis.csv",
    index=False
)

In [8]:
expense = (
    perf[
        [
            "scheme_name",
            "expense_ratio_pct"
        ]
    ]
    .sort_values(
        "expense_ratio_pct"
    )
)

expense.head(10)

                                          scheme_name  expense_ratio_pct
19  Nippon India Gilt Securities Fund - Regular - ...               0.55
9        HDFC Short Term Debt Fund - Regular - Growth               0.56
23               Kotak Liquid Fund - Regular - Growth               0.60
1            SBI Bluechip Fund - Direct Plan - Growth               0.66
3           SBI Small Cap Fund - Direct Plan - Growth               0.72
16      Nippon India Large Cap Fund - Direct - Growth               0.72
14           ICICI Pru Liquid Fund - Regular - Growth               0.74
25               Axis Bluechip Fund - Direct - Growth               0.75
4        SBI Magnum Gilt Fund - Regular Plan - Growth               0.77
8   HDFC Mid-Cap Opportunities Fund - Direct - Growth               0.78

In [9]:
expense.to_csv(
    "../reports/expense_ratio_analysis.csv",
    index=False
)

In [10]:
sharpe = (
    perf[
        [
            "scheme_name",
            "sharpe_ratio"
        ]
    ]
    .sort_values(
        by="sharpe_ratio",
        ascending=False
    )
)

sharpe.head(10)

                                          scheme_name  sharpe_ratio
14           ICICI Pru Liquid Fund - Regular - Growth          7.68
23               Kotak Liquid Fund - Regular - Growth          6.18
30                ABSL Liquid Fund - Regular - Growth          5.14
9        HDFC Short Term Debt Fund - Regular - Growth          1.84
4        SBI Magnum Gilt Fund - Regular Plan - Growth          1.52
19  Nippon India Gilt Securities Fund - Regular - ...          1.33
34      Mirae Asset Large Cap Fund - Regular - Growth          1.06
5           HDFC Top 100 Fund - Regular Plan - Growth          1.06
11          ICICI Pru Bluechip Fund - Direct - Growth          1.03
15     Nippon India Large Cap Fund - Regular - Growth          1.00

In [11]:
sharpe.to_csv(
    "../reports/fund_sharpe_ranks.csv",
    index=False
)

print("Sharpe ranking saved!")

Sharpe ranking saved!

### Insight 1
Funds with higher Sharpe Ratio delivered stronger risk-adjusted performance compared with peers, indicating better return efficiency.

In [12]:
import os

print(
    os.listdir("../reports")
)

['alpha_analysis.csv', 'charts', 'data_dictionary.md', 'expense_ratio_analysis.csv', 'fund_sharpe_ranks.csv', 'fund_sortino_ranks.csv']

In [13]:
sortino = (
    perf[
        [
            "scheme_name",
            "sortino_ratio"
        ]
    ]
    .sort_values(
        by="sortino_ratio",
        ascending=False
    )
)

sortino.head(10)

                                          scheme_name  sortino_ratio
14           ICICI Pru Liquid Fund - Regular - Growth          10.37
23               Kotak Liquid Fund - Regular - Growth           9.70
30                ABSL Liquid Fund - Regular - Growth           8.76
9        HDFC Short Term Debt Fund - Regular - Growth           2.79
19  Nippon India Gilt Securities Fund - Regular - ...           2.38
4        SBI Magnum Gilt Fund - Regular Plan - Growth           2.11
5           HDFC Top 100 Fund - Regular Plan - Growth           1.70
15     Nippon India Large Cap Fund - Regular - Growth           1.68
3           SBI Small Cap Fund - Direct Plan - Growth           1.67
34      Mirae Asset Large Cap Fund - Regular - Growth           1.66

In [14]:
sortino.to_csv(
    "../reports/fund_sortino_ranks.csv",
    index=False
)

print("Sortino ranking saved!")

Sortino ranking saved!

### Insight 2
Funds with higher Sortino Ratio generated stronger returns while controlling downside volatility more effectively.

In [15]:
import os

print(os.listdir("../reports"))

['alpha_analysis.csv', 'charts', 'data_dictionary.md', 'expense_ratio_analysis.csv', 'fund_sharpe_ranks.csv', 'fund_sortino_ranks.csv']

In [16]:
alpha = (
    perf[
        [
            "scheme_name",
            "alpha"
        ]
    ]
    .sort_values(
        by="alpha",
        ascending=False
    )
)

alpha.head(10)

                                          scheme_name  alpha
9        HDFC Short Term Debt Fund - Regular - Growth   1.98
21      Kotak Emerging Equity Fund - Regular - Growth   1.91
14           ICICI Pru Liquid Fund - Regular - Growth   1.85
22             Kotak Flexicap Fund - Regular - Growth   1.85
29             ABSL Small Cap Fund - Regular - Growth   1.84
37         DSP Top 100 Equity Fund - Regular - Growth   1.82
18                     Nippon India ETF Nifty 50 BeES   1.80
33              UTI Flexi Cap Fund - Regular - Growth   1.79
1            SBI Bluechip Fund - Direct Plan - Growth   1.78
35  Mirae Asset Emerging Bluechip Fund - Regular -...   1.70

In [17]:
alpha.to_csv(
    "../reports/alpha_analysis.csv",
    index=False
)

print("Alpha analysis saved!")

Alpha analysis saved!

### Insight 3
Funds with higher Alpha demonstrated stronger performance relative to their benchmark expectations and delivered additional value beyond market movement.

In [18]:
import os

print(os.listdir("../reports"))

['alpha_analysis.csv', 'charts', 'data_dictionary.md', 'expense_ratio_analysis.csv', 'fund_sharpe_ranks.csv', 'fund_sortino_ranks.csv']

In [19]:
expense = (
    perf[
        [
            "scheme_name",
            "expense_ratio_pct"
        ]
    ]
    .sort_values(
        by="expense_ratio_pct",
        ascending=True
    )
)

expense.head(10)

                                          scheme_name  expense_ratio_pct
19  Nippon India Gilt Securities Fund - Regular - ...               0.55
9        HDFC Short Term Debt Fund - Regular - Growth               0.56
23               Kotak Liquid Fund - Regular - Growth               0.60
1            SBI Bluechip Fund - Direct Plan - Growth               0.66
3           SBI Small Cap Fund - Direct Plan - Growth               0.72
16      Nippon India Large Cap Fund - Direct - Growth               0.72
14           ICICI Pru Liquid Fund - Regular - Growth               0.74
25               Axis Bluechip Fund - Direct - Growth               0.75
4        SBI Magnum Gilt Fund - Regular Plan - Growth               0.77
8   HDFC Mid-Cap Opportunities Fund - Direct - Growth               0.78

In [20]:
expense.to_csv(
    "../reports/expense_ratio_analysis.csv",
    index=False
)

print("Expense ratio analysis saved!")

Expense ratio analysis saved!

### Insight 4
Lower expense ratio funds provide cost-efficient investment exposure and may improve long-term net returns for investors.

In [21]:
import os

print(
    os.listdir("../reports")
)

['alpha_analysis.csv', 'charts', 'data_dictionary.md', 'expense_ratio_analysis.csv', 'fund_sharpe_ranks.csv', 'fund_sortino_ranks.csv']